name:                haskell-programming-from-first-principles
version:             0.1.0.0
github:              "BoeingX/haskell-programming-from-first-principles"
license:             BSD3
author:              "BoeingX"
maintainer:          "user@domain.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/BoeingX/haskell-programming-from-first-principles#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- containers
- bytestring
- text
- raw-strings-qq
- random
- trifecta
- parsers
- hspec
- QuickCheck
- checkers
- hspec-checkers
- split
- scotty
- wai

library:
  source-dirs: src

benchmarks:
  haskell-programming-from-first-principles-benchmark:
    dependencies:
      - base
      - criterion
    ghc-options:
      - -O2
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: 
      - src
      - benchmark

tests:
  haskell-programming-from-first-principles-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-programming-from-first-principles
